### ISSUE TITLE
P2P Review - 13/10/'22

### ISSUE THREAD

**Issue by Botlhale-Setou** [Sajeelzafar/Leaderboard#4]
Hey Sajeel 👋 

Great work on your project. Everything looks perfect!

A few suggestions:
- In your README.md file, _consider removing the highlighted segment_. I understand that text to just be instructions for **you** as the dev to read, not for public consumption.
![image](https://user-images.githubusercontent.com/11477535/195527747-63b9eebe-9b37-4694-8b01-45fb02b3d1b4.png)

- Please replace your Live Link URL with the right link.
- Consider adding semantic tags to your .HTML file.
- Consider making your webapp responsive to different screen sizes.

**Comment by Sajeelzafar** [comment]
Thankyou for your feedback, the issues are addressed and the development branch is updated.
